export interface Visita{
    id: number;
    documento: string;
    nombre: string;
    email: string;
    celular: string;
    empresa: string;
    contacto: string;
    arl: string;
    eps: string;
    area: string;
    fecha: string;
    hora: string;
    marca_equipo: string;
    serial_equipo: string;
    responsable: string;
    correo: string;
    idusuario: number;
    estado: string;
    entrada: null,
    salida: null,
    piso: null,
    transferencia: null,
    entrada2: null,
    salida2: null,
    usu_entrada1: null,
    usu_salida1: null,
    usu_entrada2: null,
    usu_salida2: null,
    date:  string;
    motivo:  string;
    piso_entrada: null,
    created_at: null,
    updated_at: null
}